version: "3"

services:
  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=reservation
    # volumes:
    #   - ./data:/data/db
    networks:
      - reservation-network

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=reservation
      - MYSQL_USER=mehul
      - MYSQL_PASSWORD=mehulpassword
    # volumes:
    #   - ./data:/var/lib/mysql
    networks:
      - reservation-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
      - PMA_PORT=3306
    networks:
      - reservation-network

  datagenerator:
    build:
      context: ./data_generator
      dockerfile: Dockerfile
    container_name: datagenerator
    depends_on:
      - mysql
    environment:
      - MYSQL_USER=mehul
      - MYSQL_PASSWORD=mehulpassword
      - MYSQL_HOST=mysql
      - MYSQL_DATABASE=reservation
    networks:
      - reservation-network

networks:
  reservation-network:
